version: '3.3'

services:

  db:
    container_name: template_db
    build:
      context: './db'
      dockerfile: Dockerfile
    ports:
      - 5436:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  server:
    container_name: template_server
    build:
      context: './server'
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app:cached
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/template
    depends_on:
      - db
    links:
      - db

  client:
    container_name: template_client
    build:
      context: './client'
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src:cached
      - ./client/public:/usr/src/app/public:cached
    ports:
      - '3001:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    links:
      - server
